extends RefCounted
class_name AstraDesktopWords
const TEXT = {
 "opponent_title":["ВРАЖЕСКИЙ КОМАНДИР","ENEMY COMMANDER","FEINDLICHER KOMMANDANT"],
 "fight":["К бою","Begin battle","Kampf beginnen"],"fight_hint":["Командир управляет армией. Уничтожьте его ядро.","The commander controls the army. Destroy their core.","Der Kommandant steuert die Armee. Zerstöre seinen Kern."],
 "research":["Технологии","Technology","Technologien"],"research_tip":["Улучшения действуют до конца путешествия. Вторая ступень открывается на Борее, третья — на Игнисе.","Upgrades last for this journey. Tier two opens on Borea; tier three on Ignis.","Verbesserungen gelten für diese Reise. Stufe zwei öffnet auf Borea, Stufe drei auf Ignis."],
 "branch_weapons":["ОРУЖИЕ","WEAPONS","WAFFEN"],"branch_frames":["КОРПУСА / БРОНЯ","FRAMES / ARMOUR","GEHÄUSE / PANZERUNG"],"branch_core":["ЯДРО КОРАБЛЯ","SHIP CORE","SCHIFFSKERN"],"branch_systems":["ЭНЕРГОСИСТЕМЫ","ENERGY SYSTEMS","ENERGIESYSTEME"],
 "research_buy":["Изучить","Research","Erforschen"],"researched":["Изучено","Researched","Erforscht"],"research_act":["После предыдущего · мир %d","Previous tier required · world %d","Vorige Stufe nötig · Welt %d"],
 "research_bought":["Технология изучена","Technology researched","Technologie erforscht"],"research_unavailable":["Нужны предыдущая ступень, нужная планета и сплав","Requires previous tier, the right world and alloy","Benötigt vorige Stufe, passende Welt und Legierung"],
 "armor":["Броня","Armour","Panzerung"],"orders_short":["Приказы: прицел или щит · 1 энергия","Orders: aim or guard · 1 energy","Befehle: Zielen oder Schutz · 1 Energie"],
 "enemy_console_hint":["HP синие · атака красная · броня жёлтая. ПКМ: крупный вид.","Blue HP · red attack · yellow armour. Right click: inspect.","LP blau · Angriff rot · Panzerung gelb. Rechtsklick: Details."],

 "new":["Новая игра","New game","Neues Spiel"],
 "desktop_subtitle":["Верните Астру. Один корабль. Пять миров.","Recover Astra. One ship. Five worlds.","Hole Astra zurück. Ein Schiff. Fünf Welten."],
 "desktop_hint":["F11 — полный экран · Ctrl +/− — размер текста · ПКМ или E — крупная карта","F11: fullscreen · Ctrl +/−: text size · Right click or E: inspect card","F11: Vollbild · Strg +/−: Textgröße · Rechtsklick oder E: Kartenansicht"],
 "small_start":["Всего 6 карт в колоде. Первый бой начнётся с одной карты и объяснения.","Just 6 cards in the deck. The first fight starts with one card and guidance.","Nur 6 Karten im Deck. Der erste Kampf beginnt mit einer Karte und Anleitung."],
 "select_deck":["Выбрать","Select","Wählen"],
 "attack_short":["АТК","ATK","ANG"],"shield_short":["Щит","Shield","Schild"],"status":["Эффект активен","Status active","Effekt aktiv"],
 "enemy_core":["ЯДРО ПРОТИВНИКА","ENEMY CORE","GEGNERKERN"],"your_core":["ВАШЕ ЯДРО","YOUR CORE","DEIN KERN"],
 "neutral_zone":["НЕЙТРАЛЬНАЯ ЗОНА","NEUTRAL ZONE","NEUTRALE ZONE"],
 "preview_hint":["Наведите мышь на карту или робота, чтобы прочитать свойства.","Hover a card or robot to read its details.","Zeige auf eine Karte oder einen Roboter, um Details zu lesen."],
 "energy_rule":["3 энергии; с 4-го хода — 4. Реакторы: ещё +1. Предел 6.","3 energy; 4 from turn 4. Reactors: +1 more. Limit 6.","3 Energie; ab Zug 4: 4. Reaktoren: +1. Grenze 6."],
 "draw_rule":["Старт: 3 карты. Добор: 1 за ход. Предел: 5 в руке.","Start: 3 cards. Draw: 1 per turn. Hand limit: 5.","Start: 3 Karten. Ziehen: 1 pro Zug. Handlimit: 5."],
 "orders_tip":["Прицел: +1 урон. Защита: щит 2. Цена 1; один приказ за ход.","Aim: +1 damage. Guard: shield 2. Cost 1; one order per turn.","Zielen: +1 Schaden. Schutz: Schild 2. Kosten 1; ein Befehl pro Zug."],
 "travel_text":["Архонт пал. След Астры ведёт дальше. Ядро восстановлено на 10 HP; колода продолжит путь с вами.","The Archon fell. Astra's trail leads onward. Core restored by 10 HP; your deck travels with you.","Der Archon ist gefallen. Astras Spur führt weiter. Kern um 10 LP geheilt; dein Deck reist mit dir."],
 "card_key":["[%d] · ПКМ","[%d] · RMB","[%d] · RMB"],
 "inspect_short":["ПКМ: подробнее","Right click: details","Rechtsklick: Details"],
 "training_rule":["В тренажёре системы появляются по очереди. Следуйте подсказке в центре. Затем откроется маршрут.","Training introduces one system at a time. Follow the central hint; the route opens afterwards.","Das Training führt Systeme einzeln ein. Folge dem Hinweis in der Mitte; danach öffnet sich die Route."],
 "inspect_key":["ПКМ / E / колесо ↑ — увеличить","Right click / E / wheel ↑: inspect","Rechtsklick / E / Mausrad ↑: ansehen"],
 "zoom_hint":["Колесо мыши меняет увеличение. Esc возвращает к бою. Чтение карты не расходует энергию.","Use the mouse wheel to zoom. Esc returns to combat. Inspection costs no energy.","Mit dem Mausrad zoomen. Esc kehrt zum Kampf zurück. Ansehen kostet keine Energie."],
 "mouse_hint":["Выберите карту → клетку. Нажмите робота для приказа. ПКМ: крупный вид.","Card → slot. Select a robot to issue an order. Right click: inspect.","Karte → Feld. Roboter wählen, um Befehle zu geben. Rechtsklick: ansehen."],
 "aim":["Прицел · 1","Aim · 1","Zielen · 1"],"guard":["Защита · 1","Guard · 1","Schutz · 1"],
 "order_help":["Прицел: +1 урон следующей атаки. Защита: щит 2 до конца хода. Один приказ роботу за ход.","Aim: +1 damage on the next attack. Guard: shield 2 for this turn. One order per robot per turn.","Zielen: +1 Schaden beim nächsten Angriff. Schutz: Schild 2 für diesen Zug. Ein Befehl pro Roboter und Zug."],
 "reinforcement":["После хода придут","Arriving after this turn","Nach diesem Zug kommen"],
 "route_desktop":["Выберите узел → «В путь». Колесо: масштаб.","Node → set course. Mouse wheel: zoom.","Knoten → aufbrechen. Mausrad: Zoom."],
 "save":["Сохранить · F5","Save · F5","Speichern · F5"],"saved":["Игра сохранена","Game saved","Spiel gespeichert"],
 "fullscreen":["Полный экран · F11","Fullscreen · F11","Vollbild · F11"],"text_size":["Размер текста","Text size","Textgröße"],
 "audio_note":["Оригинальная мелодия: мягкие клавиши, бас и арпеджио. Постоянный гул отключён. Нулевая громкость полностью останавливает музыку.","Original melody: soft keys, bass and arpeggios. The constant hum is removed. Zero volume stops music completely.","Eigene Melodie: sanfte Tasten, Bass und Arpeggien. Kein Dauersummen. Lautstärke null stoppt die Musik vollständig."],
 "training":["ТРЕНАЖЁР ИСКРЫ","SPARK TRAINING","FUNKENS TRAINING"],"skip_training":["Пропустить обучение","Skip training","Training überspringen"],"skip_story":["Перейти к обучению","Go to training","Zum Training"],
 "speaker0":["ЛИРА / бортовой интеллект","LYRA / ship intelligence","LYRA / Schiffsintelligenz"],
 "speaker1":["КАПИТАН / аварийный канал","CAPTAIN / emergency channel","KAPITÄN / Notfallkanal"],
 "speaker2":["ЛИРА / резервное питание","LYRA / backup power","LYRA / Notstrom"],
 "speaker3":["КАПИТАН / корабль «Искра»","CAPTAIN / the Spark","KAPITÄN / die Funken"],
 "story_title0":["01 / Сердце колонии","01 / Heart of the colony","01 / Das Herz der Kolonie"],
 "story_title1":["02 / Оборона прорвана","02 / Defence breached","02 / Verteidigung durchbrochen"],
 "story_title2":["03 / Астра похищена","03 / Astra stolen","03 / Astra gestohlen"],
 "story_title3":["04 / За следом ядра","04 / Follow the core","04 / Der Spur des Kerns folgen"],
 "story_text0":["Астра — сердце нашей колонии. Она хранит память людей и питает защитных роботов. «Искра» стоит у причала, пока неизвестный флот выходит из тени планеты.","Astra is our colony's heart. It holds our memories and powers the defence robots. Spark waits at the dock as an unknown fleet emerges from the planet's shadow.","Astra ist das Herz unserer Kolonie. Sie bewahrt unsere Erinnerungen und versorgt die Schutzroboter. Funken liegt am Dock, als eine fremde Flotte aus dem Planetenschatten tritt."],
 "story_text1":["Мы открываем огонь, но чужой подавитель гасит щиты. Позиции потеряны. Удержать Астру уже нельзя — капитан приказывает экипажу отступить на «Искру».","We open fire, but an alien suppressor disables our shields. The line is lost. Astra cannot be held; the captain orders everyone back to Spark.","Wir eröffnen das Feuer, doch ein fremder Störer schaltet die Schilde aus. Die Front ist verloren. Astra ist nicht zu halten; der Kapitän befiehlt den Rückzug zur Funken."],
 "story_text2":["Вражеский транспорт вытаскивает ядро из камеры. Огни колонии гаснут. Лира успевает записать сигнатуру похитителей: первый след ведёт на Вердию.","The enemy transport tears the core from its chamber. The colony goes dark. Lyra records the thieves' signature: their first trail leads to Verdia.","Der Feindtransporter reißt den Kern aus seiner Kammer. Die Kolonie wird dunkel. Lyra speichert die Signatur der Diebe: Die erste Spur führt nach Verdia."],
 "story_text3":["Резервный реактор запущен. Мы вырываемся из блокады и начинаем погоню. Сначала Лира покажет пульт: один робот, одна энергия, затем остальные системы.","The backup reactor is online. We escape the blockade and begin the chase. First, Lyra teaches the console: one robot, one energy, then the other systems.","Der Reservereaktor läuft. Wir entkommen der Blockade und nehmen die Verfolgung auf. Zuerst erklärt Lyra das Pult: ein Roboter, eine Energie, dann die übrigen Systeme."],
 "lesson0":["1. Нажмите единственную карту «Импульс», затем клетку прямо напротив врага. Она стоит 1 энергию. Можно перетащить её мышью.","1. Select the only Pulse card, then the slot opposite the enemy. It costs 1 energy. You can also drag it.","1. Wähle die einzige Impuls-Karte, dann das Feld gegenüber dem Gegner. Sie kostet 1 Energie. Ziehen ist auch möglich."],
 "lesson1":["2. Энергия потрачена. Нажмите «Завершить ход» или пробел: ваш робот атакует первым, затем отвечает выживший враг.","2. Your energy is spent. End the turn, or press Space: your robot attacks first, then surviving enemies respond.","2. Die Energie ist verbraucht. Beende den Zug oder drücke die Leertaste: Dein Roboter greift zuerst an, überlebende Gegner antworten."],
 "lesson2":["Наблюдайте за атакой. Здоровье роботов находится под ними; большие шкалы показывают состояние ядер.","Watch the attack. Robot health is below each robot; the large bars show core health.","Beobachte den Angriff. Roboter-LP stehen unter ihnen; die großen Balken zeigen die Kerne."],
 "lesson3":["3. Теперь 2 энергии и одна новая карта: «Реактор». Поставьте его в другую свободную клетку. Со следующего хода он даст +1 энергию.","3. Now you have 2 energy and one new card: Reactor. Place it in another empty slot. It adds 1 energy from the next turn.","3. Jetzt hast du 2 Energie und eine neue Karte: Reaktor. Stelle ihn auf ein anderes freies Feld. Ab dem nächsten Zug gibt er 1 Energie dazu."],
 "lesson4":["4. Завершите ход. У робота напротив теперь пусто: его атака уменьшит здоровье вражеского ядра.","4. End the turn. Your robot now faces an empty slot: its attack damages the enemy core.","4. Beende den Zug. Gegenüber deinem Roboter ist es nun leer: Sein Angriff beschädigt den Gegnerkern."],
 "lesson5":["5. Осталось уничтожить ядро. После тренировки начнётся маршрут. В обычном бою выбирайте: новая карта или приказ роботу за 1 энергию.","5. Finish the enemy core. The route opens after training. In real combat, choose between a new card and a robot order costing 1 energy.","5. Zerstöre den Gegnerkern. Danach öffnet sich die Route. Im echten Kampf wählst du zwischen einer neuen Karte und einem Roboterbefehl für 1 Energie."],
 "retreat":["Отступить на «Искру»","Retreat to Spark","Zur Funken zurückziehen"]
}
static func get_text(key: String, language: String) -> String:
 return AstraCards.word(TEXT[key],language) if TEXT.has(key) else AstraWords.get_text(key,language)
