extends RefCounted
class_name AstraRivals
const NAMES = [["Маршал Терн","Marshal Thorn","Marschall Dorn"],["Леди Вега","Lady Vega","Lady Vega"],["Гелион","Helion","Helion"],["Сераф","Seraph","Seraph"],["Нулевой разум","The Zero Mind","Der Nullgeist"]]
const TITLES = [["Хранитель корневого фронта","Warden of the root front","Wächter der Wurzelfront"],["Командующая ледяным флотом","Commander of the ice fleet","Kommandantin der Eisflotte"],["Владыка плавильных машин","Lord of the furnace machines","Herr der Schmelzmaschinen"],["Собиратель древних механизмов","Collector of ancient engines","Sammler alter Maschinen"],["Голос похитителей Астры","Voice of Astra's thieves","Stimme von Astras Dieben"]]
const TAUNTS = [
 [["Зря ты сюда явился, капитан. Корни сомкнутся вокруг твоего корабля.","You should not have come, captain. The roots will close around your ship.","Du hättest nicht kommen sollen, Kapitän. Die Wurzeln werden dein Schiff umschließen."],["Твоя Астра уже далеко. Посмотрим, как долго проживут твои машины.","Your Astra is already far away. Let's see how long your machines survive.","Deine Astra ist längst weit weg. Mal sehen, wie lange deine Maschinen überleben."],["Мои сборщики питаются обломками. Сейчас я преподам тебе урок.","My collectors feed on wreckage. It is time I taught you a lesson.","Meine Sammler ernähren sich von Wracks. Jetzt erteile ich dir eine Lektion."]],
 [["Борея не прощает слабых. Твой реактор остынет первым.","Borea does not forgive weakness. Your reactor will be the first to freeze.","Borea verzeiht keine Schwäche. Dein Reaktor wird als Erster gefrieren."],["Я заморозила целый флот. Один корабль меня не остановит.","I froze an entire fleet. One ship will not stop me.","Ich habe eine ganze Flotte eingefroren. Ein Schiff hält mich nicht auf."],["Под этим льдом много капитанов. Скоро станет на одного больше.","Many captains lie beneath this ice. Soon there will be one more.","Unter diesem Eis liegen viele Kapitäne. Bald kommt einer dazu."]],
 [["Добро пожаловать в мою кузницу. Твои роботы станут новым сплавом.","Welcome to my forge. Your robots will become fresh alloy.","Willkommen in meiner Schmiede. Deine Roboter werden zu neuer Legierung."],["Чувствуешь жар? Это твоя последняя остановка.","Feel the heat? This is your final stop.","Spürst du die Hitze? Das ist deine letzte Station."],["Мои машины не боятся огня. А твои?", "My machines do not fear fire. Do yours?","Meine Maschinen fürchten kein Feuer. Und deine?"]],
 [["В этих руинах всё принадлежит мне. Даже то, что ты ещё не потерял.","Everything in these ruins belongs to me. Even what you haven't lost yet.","In diesen Ruinen gehört alles mir. Auch das, was du noch nicht verloren hast."],["Я знаю цену твоему ядру. Давай проверим цену твоей смелости.","I know the price of your core. Let's test the price of your courage.","Ich kenne den Preis deines Kerns. Prüfen wir den Preis deines Mutes."],["Песок скроет следы твоего корабля. Погоня закончится здесь.","The sand will erase your ship's trail. The chase ends here.","Der Sand verwischt die Spur deines Schiffs. Die Jagd endet hier."]],
 [["Я уже вычислил исход этого боя. Тебя в нём больше нет.","I have already calculated this battle's outcome. You are no longer in it.","Ich habe den Ausgang dieses Kampfes berechnet. Du kommst darin nicht mehr vor."],["Астра стала частью меня. Ты не заберёшь её обратно.","Astra has become part of me. You will not take her back.","Astra ist ein Teil von mir geworden. Du bekommst sie nicht zurück."],["Твои машины помнят тебя. Скоро я сотру эту память.","Your machines remember you. Soon I will erase that memory.","Deine Maschinen erinnern sich an dich. Bald lösche ich diese Erinnerung."]]
]
static func name_for(act: int, language: String) -> String:
 return AstraCards.word(NAMES[act],language)
static func line_for(battle: Dictionary, language: String) -> String:
 return AstraCards.word(TAUNTS[int(battle.act)][int(battle.get("taunt",0))%3],language)
